name: Example 02 - Code Formatting with Laravel Pint
run-name: Example 02 - Code Formatting with Laravel Pint

on: 
  push:
    branches:
      - master

jobs:
  run-pint-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      # - name: install PHP & Composer (IF YOU WANT)
      
      - name: install laravel pint
        run: composer require laravel/pint --dev
      
      - name: run pint
        run: ./vendor/bin/pint
      
      - name: commit changes back
        run: |
          git config --local user.email "www.bk3344@gmail.com"
          git config --local user.name "belalkhaledmohameed"
          git add .
          git commit -m "Run Pint updated" || exit 0
          git push 





