name: Example 07 - Deployment
run-name: Example 07 - Deployment

on: 
  # push:
  #   branches:
  #     - production
  workflow_dispatch:
    

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH key
        run: |
          mkdir -p ~/Downloads
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/Downloads/Dploy-pipeline.pem
          chmod 400 ~/Downloads/Dploy-pipeline.pem
          ssh-keyscan -H 98.80.234.69 >> ~/.ssh/known_hosts
      
      - name: Deploy to Google Cloud
        run: |
          cd ~/Downloads
          ssh -i "Dploy-pipeline.pem"  ubuntu@98.80.234.69 "mkdir ~/Project && cd ~/Project/ && git init && git clone https://github.com/belalkhaledmohameed/CI-CD-Project.git && cd ~/Project/CI-CD-Project && git pull origin master"




